name: 'reusable/analysis'

on:
  workflow_call:
    inputs:
      moduleRootDirectory:
        description: 'Defines root module directory'
        required: true
        type: string

    secrets:
      githubToken:
        description: 'GitHub Token value'
        required: true

jobs:
  checkov:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.moduleRootDirectory }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Scan module with checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: ${{ inputs.moduleRootDirectory }}
          quiet: false
          soft_fail: false
          compact: false
          skip_check: CKV_GCP_80,CKV_GCP_81,CKV_TF_1,CKV_GCP_121,CKV_GCP_82,CKV_GCP_43,CKV_GCP_62,CKV_GCP_114,CKV_GCP_103,CKV_GCP_83,CKV_GCP_124

  # tfsec:
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       working-directory: ${{ inputs.moduleRootDirectory }}
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v7

  #     - name: Scan module with tfsec
  #       uses: aquasecurity/tfsec-action@v1.0.3
  #       with:
  #         working_directory: ${{ inputs.moduleRootDirectory }}
  #         github_token: ${{ secrets.githubToken }}
